// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd0GMtMpq2cWbURvBCR0FxxaXnyzNCAAc',
    appId: '1:527166467957:web:f1f3048bdf4a5c6cc8ed3c',
    messagingSenderId: '527166467957',
    projectId: 'you-m11',
    authDomain: 'you-m11.firebaseapp.com',
    storageBucket: 'you-m11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SIThRm7t6DzGTAsNW9i5KmNEZujEAxU',
    appId: '1:527166467957:android:4cfc2a08807b484ac8ed3c',
    messagingSenderId: '527166467957',
    projectId: 'you-m11',
    storageBucket: 'you-m11.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd0GMtMpq2cWbURvBCR0FxxaXnyzNCAAc',
    appId: '1:527166467957:web:2ff696dd257afb59c8ed3c',
    messagingSenderId: '527166467957',
    projectId: 'you-m11',
    authDomain: 'you-m11.firebaseapp.com',
    storageBucket: 'you-m11.firebasestorage.app',
  );
}
